"""empty message

Revision ID: 49a962478b64
Revises: 1d3205518d40
Create Date: 2023-04-22 18:13:07.600400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a962478b64'
down_revision = '1d3205518d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customerID', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favoritos_customer_ID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerID'], ['customerID'])
        batch_op.drop_column('customer_ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_ID', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_customer_ID_fkey', 'customers', ['customer_ID'], ['customerID'])
        batch_op.drop_column('customerID')

    # ### end Alembic commands ###
